# Generated by Django 2.0.2 on 2018-02-05 06:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductQualityScoreData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pq_scores', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazonapp.Category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazonapp.Product')),
                ('product_quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazonapp.ProductQuality')),
            ],
        ),
        migrations.CreateModel(
            name='ProductQualitySnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazonapp.Category')),
                ('product', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='amazonapp.Product')),
                ('product_quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazonapp.ProductQuality')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_id', models.CharField(max_length=255)),
                ('num_helpful', models.IntegerField(default=0)),
                ('num_unhelpful', models.IntegerField(default=0)),
                ('review_text', models.TextField()),
                ('star_rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('summary', models.TextField()),
                ('review_time', models.CharField(max_length=255)),
                ('product', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='amazonapp.Product')),
            ],
        ),
        migrations.AddField(
            model_name='productqualitysnippet',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazonapp.Review'),
        ),
    ]
