# Generated by Django 2.0.2 on 2018-02-05 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazonapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQualityScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazonapp.Category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazonapp.Product')),
                ('product_quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazonapp.ProductQuality')),
            ],
        ),
        migrations.RemoveField(
            model_name='productqualityscoredata',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productqualityscoredata',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productqualityscoredata',
            name='product_quality',
        ),
        migrations.DeleteModel(
            name='ProductQualityScoreData',
        ),
    ]
