# Generated by Django 2.0.2 on 2018-03-13 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazonapp', '0002_auto_20180205_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productqualityscore',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='amazonapp.Category'),
        ),
    ]
