# Generated by Django 2.0.2 on 2018-03-31 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazonapp', '0006_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
